### ISSUE TITLE
D-Series: Movie logos are not scaled

### ISSUE THREAD

**Issue by arcticwaters** [MediaBrowser/SamsungSmartTV#16]
On a movies detail page just before you go to play, the logo shown is not scaled to properly fit in the sized div. The movie logo appears too big with cutoff edges (depending on the logo). This isn't visible on the emulator, so it must be related to the older d-series tv. I suspect it has to with new CSS rules not supported on the d-series introduced in 2.x.

Last known good release: 1.0.1

**Comment by cmcgerty** [comment]
Hi,

I'm sorry if you've spent time testing this on your D-Series TV. D-Series support was ended at version 2.0.0 in order to allow a transition to HTML5 and CSS3.

http://emby.media/community/index.php?/topic/31056-2011-d-series-support-ending/

Version 1.0.6 has been retained to provide long term support for D-Series devices but will not be actively developed. It can be installed from 162.254.68.24.

**Comment by arcticwaters** [comment]
Closing since d-series patches will not be merged.
