### ISSUE TITLE
Movie info for 3D movies not scaled

### ISSUE THREAD

**Issue by arcticwaters** [MediaBrowser/SamsungSmartTV#17]
For movies which the server has identified as 3d, the app automatically switches on 3d-mode. For D-series at least, the resolution changes when 3d mode is enabled (side-by-side mode tested). When the `info` button is pressed, the movie information interface is drawn for the 1080p causing everything to look too large, hiding information that doesn't fit on screen.

We'll have to use more relative sizes in the CSS if we want to fix this, but this has implications for the entire app.

This includes the playback options shown when `tools` is pressed.

**Comment by cmcgerty** [comment]
Hi,

I'm sorry if you've spent time testing this on your D-Series TV. D-Series support was ended at version 2.0.0 in order to allow a transition to HTML5 and CSS3.

http://emby.media/community/index.php?/topic/31056-2011-d-series-support-ending/

Version 1.0.6 has been retained to provide long term support for D-Series devices but will not be actively developed. It can be installed from 162.254.68.24.

**Comment by arcticwaters** [comment]
Has 3d mode changed in the newer tv models such that is doesn't require a resolution switch? I think this might still be relevant. I don't have a device to actually test this. Close this if its handled differently.

**Comment by cmcgerty** [comment]
I don't know. If you ask in the Emby forum Elysium is a good guy to ask about 3D content on Samsung.
