### ISSUE TITLE
D-Series: Breaking changes 2.1.2+

### ISSUE THREAD

**Issue by arcticwaters** [MediaBrowser/SamsungSmartTV#18]
There are a few breaking changes for D-Series users in the 2.1.2 release.
- Can no longer play videos. The loading div appears, but nothing plays. No blank screen. After a few button presses, we can navigate app again and the loading div remains onscreen.
- Can no longer distinguish which item is selected. Only the number in the bottom left gives any visual cue that a change has occurred. The zoom effect is not visible.

No so much breaking, but visible:
- Backdrop no longer fades in. Appears to swap from grey to the shown image (this may just be because the tv is slow).

Note that all these appear to function as intended on the emulator. They just appear broken on the D-Series.

Last known working version: 2.0.7.

**Comment by cmcgerty** [comment]
Hi,

I'm sorry if you've spent time testing this on your D-Series TV. D-Series support was ended at version 2.0.0 in order to allow a transition to HTML5 and CSS3.

http://emby.media/community/index.php?/topic/31056-2011-d-series-support-ending/

Version 1.0.6 has been retained to provide long term support for D-Series devices but will not be actively developed. It can be installed from 162.254.68.24.

**Comment by arcticwaters** [comment]
Missed that post. False alarm then.

Will you still accept d-series patches that don't interfere with the new development?

**Comment by cmcgerty** [comment]
I'd rather not. You can always fork it.

**Comment by arcticwaters** [comment]
Gonna close this then.
